description: GPT-2 Recipe Generation on V100

target:
  # which virtual cluster you belong to (msrlabs, etc.). Everyone has access to "msrlabs".
  vc: resrchprojvc19
  # physical cluster to use (cam, gcr, rr1, rr2) or Azure clusters (eu1, eu2, etc.)
  cluster: rr1

environment:
  image: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  registry: phillyregistry.azurecr.io
  setup:
  - source setup.sh

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/src

data:
  local_dir: $CONFIG_DIR/data
  remote_dir: gpt2-recipe-gen-data

# list of jobs to run
jobs:
  # name must be unique across the jobs
- name: gpt2-md-512-2
  # one gpu
  sku: G8
  command:
  # model_name_or_path=gpt2, gpt2-medium, gpt2-large, gpt2-xl
  - python main.py --model_type=gpt2
    --model_name_or_path=gpt2-medium
    --overwrite_output_dir
    --do_train
    --do_eval
    --save_steps=10000
    --save_total_limit=5
    --num_train_epochs=1
    --block_size=512
    --per_gpu_train_batch_size=2
    --per_gpu_eval_batch_size=2
